// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
// Do not edit! See https://mongoose.ws/documentation/#overriding-default-glue-callbacks
struct Sensors s_Sensors = {"", "", 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 10, 3, true, false, false, false};
void glue_get_Sensors(struct Sensors *data) {
  *data = s_Sensors;  // Sync with your device
}
void glue_set_Sensors(struct Sensors *data) {
  s_Sensors = *data; // Sync with your device
}

// Do not edit! See https://mongoose.ws/documentation/#overriding-default-glue-callbacks
static uint64_t s_action_timeout_save_event;  // Time when save_event ends
bool glue_check_save_event(void) {
  return s_action_timeout_save_event > mg_now(); // Return true if save_event is in progress
}
void glue_start_save_event(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_save_event = mg_now() + 1000; // Start save_event, finish after 1 second
}

void glue_reply_events(struct mg_connection *c, struct mg_http_message *hm) {
  const char *headers = "Cache-Control: no-cache\r\n" "Content-Type: application/json\r\n";
  const char *value = "[{\"id\":0,\"timestamp\":12345,\"message\":\"Something failed\",\"priority\":2,\"status\":\"active\",\"notes\":\"some notes\"},{\"id\":1,\"timestamp\":12395,\"message\":\"Something succeeded\",\"priority\":1,\"status\":\"processed\",\"notes\":\"\"}]";
  (void) hm;
  mg_http_reply(c, 200, headers, "%s\n", value);
}